Pull in contributors data at build time
tableflip/libp2p-website pull request #9
Opened 2017-06-20 15:24 UTC by olizilla

- Use hugo's getJSON function to grab contributors data at build time.
- Simplify contributors impl

2017-06-20 15:30 UTC, alanshaw commented
👓

2017-06-20 15:56 UTC, alanshaw requested changes
:thumbsup: looking good and working great

2017-06-20 15:56 UTC, alanshaw commented on layouts/partials/contributors.html
> +  }
can remove?

2017-06-20 15:56 UTC, alanshaw commented on layouts/partials/contributors.html
> +      }
If the image fails to load you halt the animation I think. You need an `onerror` handler to call the callback in this case.

2017-06-20 15:56 UTC, alanshaw commented on layouts/partials/contributors.html
> +      renderWithPause(0, Date.now())
Feels like you could extract this control flow logic from the rendering and publish as a module ;)

2017-06-20 17:00 UTC, olizilla commented
Fixed up!

2017-06-20 17:00 UTC, merged

2017-06-21 08:51 UTC, alanshaw commented on layouts/partials/contributors.html
> +          if (err) renderWithPause(nextIndex)
Should this `return renderWIthPause(/* ... */)` here?

2017-06-21 08:51 UTC, alanshaw commented on layouts/partials/contributors.html
> +            renderWithPause(itemIndex + 1)
use `nextIndex`?